### ISSUE TITLE
doesnt load any webpages

### ISSUE THREAD

**Issue by magonyfur** [Varkaria/guweb#50]
the error prompt

[2023-10-05 09:59:29 +0200] [18169] [INFO] Running on http://127.0.0.1:8000 (CTRL + C to quit)
[2023-10-05 09:59:34,250] ERROR in app: Exception on request GET /
Traceback (most recent call last):
  File "/home/magsec/.local/lib/python3.9/site-packages/quart/app.py", line 1358, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/home/magsec/.local/lib/python3.9/site-packages/quart/app.py", line 1396, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "/home/magsec/.local/lib/python3.9/site-packages/quart/app.py", line 999, in handle_user_exception
    raise error
  File "/home/magsec/.local/lib/python3.9/site-packages/quart/app.py", line 1394, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/home/magsec/.local/lib/python3.9/site-packages/quart/app.py", line 1488, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)
  File "/home/magsec/guweb/blueprints/frontend.py", line 45, in home
    return await render_template('home.html')
  File "/home/magsec/.local/lib/python3.9/site-packages/quart/templating.py", line 46, in render_template
    template = current_app.jinja_env.get_or_select_template(template_name_or_list)  # type: ignore
  File "/home/magsec/.local/lib/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/magsec/.local/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/magsec/.local/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/magsec/.local/lib/python3.9/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/magsec/.local/lib/python3.9/site-packages/flask/templating.py", line 63, in get_source
    if self.app.config["EXPLAIN_TEMPLATE_LOADING"]:
KeyError: 'EXPLAIN_TEMPLATE_LOADING'

**Comment by 7ez** [comment]
update quart

**Comment by magonyfur** [comment]
with pip i think

**Comment by magonyfur** [comment]
an other question, im beta testing is WSL ubuntu can i connect from my windows osu to there?

**Comment by TheFantasticLoki** [comment]
> an other question, im beta testing is WSL ubuntu can i connect from my windows osu to there?

as long as you make the proper host file edits
