### ISSUE TITLE
upon executing 'python3.9 main.py

### ISSUE THREAD

**Issue by kiyosgambling** [Varkaria/guweb#51]
upon executing '`python3.9 main.py`' i get this, any fix?

 * Serving Quart app 'main'
 * Debug mode: False
 * Please use an ASGI server (e.g. Hypercorn) directly in production
 * Running on http://127.0.0.1:8000 (CTRL + C to quit)
[2024-03-23 13:01:33,429] ERROR in app: Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/quart/app.py", line 1671, in startup
    await self.ensure_async(func)()
  File "/home/kiyo/osu-nuts/guweb/main.py", line 31, in mysql_conn
    await glob.db.connect(glob.config.mysql) # type: ignore
  File "/usr/local/lib/python3.9/dist-packages/cmyui/mysql.py", line 37, in connect
    self.pool = await aiomysql.create_pool(**config, autocommit=True)
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/pool.py", line 29, in _create_pool
    await pool._fill_free_pool(False)
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/pool.py", line 182, in _fill_free_pool
    conn = await connect(echo=self._echo, loop=self._loop,
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/connection.py", line 75, in _connect
    await conn._connect()
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/connection.py", line 540, in _connect
    await self._request_authentication()
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/connection.py", line 855, in _request_authentication
    await self._process_auth(plugin_name, auth_packet)
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/connection.py", line 907, in _process_auth
    pkt = await self._read_packet()
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/connection.py", line 652, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.9/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.9/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'kiyo'@'localhost' (using password: YES)")
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/quart/asgi.py", line 320, in __call__
    await self.app.startup()
  File "/usr/local/lib/python3.9/dist-packages/quart/app.py", line 1671, in startup
    await self.ensure_async(func)()
  File "/home/kiyo/osu-nuts/guweb/main.py", line 31, in mysql_conn
    await glob.db.connect(glob.config.mysql) # type: ignore
  File "/usr/local/lib/python3.9/dist-packages/cmyui/mysql.py", line 37, in connect
    self.pool = await aiomysql.create_pool(**config, autocommit=True)
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/pool.py", line 29, in _create_pool
    await pool._fill_free_pool(False)
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/pool.py", line 182, in _fill_free_pool
    conn = await connect(echo=self._echo, loop=self._loop,
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/connection.py", line 75, in _connect
    await conn._connect()
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/connection.py", line 540, in _connect
    await self._request_authentication()
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/connection.py", line 855, in _request_authentication
    await self._process_auth(plugin_name, auth_packet)
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/connection.py", line 907, in _process_auth
    pkt = await self._read_packet()
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/connection.py", line 652, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.9/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.9/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'kiyo'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kiyo/osu-nuts/guweb/main.py", line 74, in <module>
    app.run(port=8000, debug=glob.config.debug) # blocking call
  File "/usr/local/lib/python3.9/dist-packages/quart/app.py", line 850, in run
    loop.run_until_complete(asyncio.gather(*tasks))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/hypercorn/asyncio/__init__.py", line 44, in serve
    await worker_serve(
  File "/usr/local/lib/python3.9/dist-packages/hypercorn/asyncio/run.py", line 87, in worker_serve
    raise exception
  File "/usr/local/lib/python3.9/dist-packages/hypercorn/asyncio/lifespan.py", line 43, in handle_lifespan
    await self.app(
  File "/usr/local/lib/python3.9/dist-packages/hypercorn/app_wrappers.py", line 34, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/quart/app.py", line 1638, in __call__
    await self.asgi_app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/quart/app.py", line 1664, in asgi_app
    await asgi_handler(receive, send)
  File "/usr/local/lib/python3.9/dist-packages/quart/asgi.py", line 322, in __call__
    await send(
  File "/usr/local/lib/python3.9/dist-packages/hypercorn/asyncio/lifespan.py", line 101, in asgi_send
    raise LifespanFailureError("startup", message.get("message", ""))
hypercorn.utils.LifespanFailureError: Lifespan failure in startup. '(1045, "Access denied for user 'kiyo'@'localhost' (using password: YES)")'

**Comment by 7ez** [comment]
kiyo I think the error is self explainable
you do not have access to the database on your account

**Comment by kiyosgambling** [comment]
right i understand that part, but i just dont know how to give myself access

**Comment by 7ez** [comment]
`sudo mysql`
`grant all on *.* to 'kiyo'@'localhost';`
`exit`

**Comment by kiyosgambling** [comment]
still getting the same error

**Comment by 7ez** [comment]
are u using docker

**Comment by kiyosgambling** [comment]
unsure

**Comment by kiyosgambling** [comment]
i think i am
